### ISSUE TITLE
Readme上的图片是如何做的

### ISSUE THREAD

**Issue by owen800q** [fresns/wechat#3]
![IMG_6860](https://github.com/fresns/wechat/assets/19252045/0bc3d569-6ceb-48d1-8ee9-64000e3577ff)

Hi, 可以分享下这个图片是如何做的嗎，用第三方工具生成？

**Comment by jevantang** [comment]
网上找 Mockups，找到喜欢的使用 Photoshop 或 Photopea 等设计工具制作。
